### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by SonwYang** [wuchangsheng951/satellite_segmentaion#3]
Hello!I have a new questions when I run your code.The details are as follows:
`Traceback (most recent call last):
  File "train.py", line 178, in <module>
    train_hist = train(train_loader, num_classes, device, net, optimizer, criterion)
  File "train.py", line 117, in train
    loss = criterion(outputs, masks)
  File "/home/yp/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/yp/My Passport/dl_code2/satellite_segmentaion-master/utils/loss.py", line 84, in forward
    return max(miou, self.nll_loss(nn.functional.log_softmax(inputs, dim=1), targets))
RuntimeError: CUDA error: device-side assert triggered
`
I just want to extract building so I set  num_class equal to 2.Can you give me some suggestions to solve it? Thank you.

**Comment by SonwYang** [comment]
When I choose cpu, the error is:`Traceback (most recent call last): File "train.py", line 184, in <module> train_hist = train(train_loader, num_classes, device, net, optimizer, criterion) File "train.py", line 123, in train loss = criterion(outputs, masks) File "/home/yp/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__ result = self.forward(*input, **kwargs) File "/media/yp/My Passport/dl_code2/satellite_segmentaion-master/utils/loss.py", line 76, in forward masks = torch.zeros(N, C, H, W).to(targets.device).scatter_(1, targets.view(N, 1, H, W), 1).permute(1, 0, 2, 3) RuntimeError: Invalid index in scatter at /opt/conda/conda-bld/pytorch_1550802451070/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:549`
